// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI48QgO_ZPmeLaOAc7Cor2ex3akcQHe68',
    appId: '1:261748112904:web:153ab806ef8b85cbde1bbd',
    messagingSenderId: '261748112904',
    projectId: 'flutterproject-6cbcc',
    authDomain: 'flutterproject-6cbcc.firebaseapp.com',
    storageBucket: 'flutterproject-6cbcc.appspot.com',
    measurementId: 'G-RH0DLYFVN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvUz_NuEB0IQZ4UKi5JQp3xR-S4ol05gs',
    appId: '1:261748112904:android:abfa03da6b8f2290de1bbd',
    messagingSenderId: '261748112904',
    projectId: 'flutterproject-6cbcc',
    storageBucket: 'flutterproject-6cbcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjqoup3tO8eNRirWzgIaIas9i7H9VtzE4',
    appId: '1:261748112904:ios:0c1641d438ca85f6de1bbd',
    messagingSenderId: '261748112904',
    projectId: 'flutterproject-6cbcc',
    storageBucket: 'flutterproject-6cbcc.appspot.com',
    iosClientId: '261748112904-rshom3afvgtab1m1rkdnl5vnkn5h9l30.apps.googleusercontent.com',
    iosBundleId: 'com.example.project2022',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjqoup3tO8eNRirWzgIaIas9i7H9VtzE4',
    appId: '1:261748112904:ios:0c1641d438ca85f6de1bbd',
    messagingSenderId: '261748112904',
    projectId: 'flutterproject-6cbcc',
    storageBucket: 'flutterproject-6cbcc.appspot.com',
    iosClientId: '261748112904-rshom3afvgtab1m1rkdnl5vnkn5h9l30.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
